### ISSUE TITLE
Add emojis for each section

### ISSUE THREAD

**Issue by JuliaLehoux** [zenika-open-source/awesome-remote-work#39]
**Context**

@jlandure loves emojis as he suggested in #38

**Comment by aceol** [comment]
I was going to create the issue 😁

**Comment by JuliaLehoux** [comment]
I've just added some emojis to the big sections, is it what you expected?

**Comment by jlandure** [comment]
Hey @JuliaLehoux 👋 

Yes exactly! I also invite you to add emojis in the 2 others files. 👍 

Thanks for the contribution. 💚
